use_frameworks!

platform :ios, '10.0'

target 'WHMemoryLeakManager_Example' do
  pod 'WHMemoryLeakManager', :path => '../'

  target 'WHMemoryLeakManager_Tests' do
    inherit! :search_paths

    
  end
end
